- name: configuring cart server
  hosts: cart
  become: yes
  tasks:
  - name: Disabling default nodejs version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling required nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing Nodejs
    ansible.builtin.package:
      name: nodejs
      state: installed

  - name: Creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: creating roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app
      state: present

  - name: Download application code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: Unzip the code
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: Copying cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable cart
    ansible.builtin.service:
      name: cart
      state: started
      enabled: yes