- name: configuring catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: Disabling Nodejs default version
    ansible.builtin.command: dnf module disable nodejs -y

  - name: Enabling Nodejs version 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing Nodejs
    ansible.builtin.package: 
      name: nodejs
      state: installed
  
  - name: Adding system user roboshop
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      state: present
      home: /app

  - name: Creating app directory
    ansible.builtin.file:
      path: /etc/app
      state: directory

  - name: Download the code 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip

  - name: Unzip the catalogue code
    ansible.builtin.unarchieve:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: Copying catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: Start and enable catalogue service
    ansible.builtin.systemd_service:
      name: catalogue
      state: started
      enabled: yes

  - name: Copying mongo repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh
      state: installed

  - name: check products loaded or not
    ansible.builtin.command: mongosh --host mongodb.daws84s.site --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
    register: catalogue_output

  - name: Print the output
    ansible.builtin.debug:
      msg: "{{ catalogue_output }}"

  - name: Load the master data
    ansible.builtin.command: mongosh --host mongodb.bittu27.site </app/db/master-data.js
    when: catalogue_output.stdout | int < 0


  