- name: configuring MongoDB server
  hosts: mongodb
  become: yes
  tasks:
  - name: Copying mongo repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Installing MongoDB
    ansible.builtin.package:
      name: mongodb-org
      state: installed

  - name: Start MongoDB
    ansible.builtin.service:
      name: mongodb-org
      state: started
      enabled: yes